// This file was generated by Rcpp::compileAttributes
// Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

#include <Rcpp.h>

using namespace Rcpp;

// cppREG
List cppREG(NumericVector p, NumericVector xpar, NumericMatrix xi, float g, float k);
RcppExport SEXP nim_cppREG(SEXP pSEXP, SEXP xparSEXP, SEXP xiSEXP, SEXP gSEXP, SEXP kSEXP) {
BEGIN_RCPP
    Rcpp::RObject __result;
    Rcpp::RNGScope __rngScope;
    Rcpp::traits::input_parameter< NumericVector >::type p(pSEXP);
    Rcpp::traits::input_parameter< NumericVector >::type xpar(xparSEXP);
    Rcpp::traits::input_parameter< NumericMatrix >::type xi(xiSEXP);
    Rcpp::traits::input_parameter< float >::type g(gSEXP);
    Rcpp::traits::input_parameter< float >::type k(kSEXP);
    __result = Rcpp::wrap(cppREG(p, xpar, xi, g, k));
    return __result;
END_RCPP
}
// cppREG_lin
List cppREG_lin(NumericVector p, NumericVector xpar, NumericMatrix xi, float g, float k);
RcppExport SEXP nim_cppREG_lin(SEXP pSEXP, SEXP xparSEXP, SEXP xiSEXP, SEXP gSEXP, SEXP kSEXP) {
BEGIN_RCPP
    Rcpp::RObject __result;
    Rcpp::RNGScope __rngScope;
    Rcpp::traits::input_parameter< NumericVector >::type p(pSEXP);
    Rcpp::traits::input_parameter< NumericVector >::type xpar(xparSEXP);
    Rcpp::traits::input_parameter< NumericMatrix >::type xi(xiSEXP);
    Rcpp::traits::input_parameter< float >::type g(gSEXP);
    Rcpp::traits::input_parameter< float >::type k(kSEXP);
    __result = Rcpp::wrap(cppREG_lin(p, xpar, xi, g, k));
    return __result;
END_RCPP
}
// cppREG_constK
List cppREG_constK(NumericVector p, NumericVector xpar, NumericMatrix xi, float g, float k);
RcppExport SEXP nim_cppREG_constK(SEXP pSEXP, SEXP xparSEXP, SEXP xiSEXP, SEXP gSEXP, SEXP kSEXP) {
BEGIN_RCPP
    Rcpp::RObject __result;
    Rcpp::RNGScope __rngScope;
    Rcpp::traits::input_parameter< NumericVector >::type p(pSEXP);
    Rcpp::traits::input_parameter< NumericVector >::type xpar(xparSEXP);
    Rcpp::traits::input_parameter< NumericMatrix >::type xi(xiSEXP);
    Rcpp::traits::input_parameter< float >::type g(gSEXP);
    Rcpp::traits::input_parameter< float >::type k(kSEXP);
    __result = Rcpp::wrap(cppREG_constK(p, xpar, xi, g, k));
    return __result;
END_RCPP
}
// cppREG_constGK
List cppREG_constGK(NumericVector p, NumericVector xpar, NumericMatrix xi, float g, float k);
RcppExport SEXP nim_cppREG_constGK(SEXP pSEXP, SEXP xparSEXP, SEXP xiSEXP, SEXP gSEXP, SEXP kSEXP) {
BEGIN_RCPP
    Rcpp::RObject __result;
    Rcpp::RNGScope __rngScope;
    Rcpp::traits::input_parameter< NumericVector >::type p(pSEXP);
    Rcpp::traits::input_parameter< NumericVector >::type xpar(xparSEXP);
    Rcpp::traits::input_parameter< NumericMatrix >::type xi(xiSEXP);
    Rcpp::traits::input_parameter< float >::type g(gSEXP);
    Rcpp::traits::input_parameter< float >::type k(kSEXP);
    __result = Rcpp::wrap(cppREG_constGK(p, xpar, xi, g, k));
    return __result;
END_RCPP
}
// cppREG_const
List cppREG_const(NumericVector p, NumericVector xpar, NumericMatrix xi, float g, float k);
RcppExport SEXP nim_cppREG_const(SEXP pSEXP, SEXP xparSEXP, SEXP xiSEXP, SEXP gSEXP, SEXP kSEXP) {
BEGIN_RCPP
    Rcpp::RObject __result;
    Rcpp::RNGScope __rngScope;
    Rcpp::traits::input_parameter< NumericVector >::type p(pSEXP);
    Rcpp::traits::input_parameter< NumericVector >::type xpar(xparSEXP);
    Rcpp::traits::input_parameter< NumericMatrix >::type xi(xiSEXP);
    Rcpp::traits::input_parameter< float >::type g(gSEXP);
    Rcpp::traits::input_parameter< float >::type k(kSEXP);
    __result = Rcpp::wrap(cppREG_const(p, xpar, xi, g, k));
    return __result;
END_RCPP
}
// cppXI0
List cppXI0(float p, NumericVector xi, NumericVector g, NumericVector k);
RcppExport SEXP nim_cppXI0(SEXP pSEXP, SEXP xiSEXP, SEXP gSEXP, SEXP kSEXP) {
BEGIN_RCPP
    Rcpp::RObject __result;
    Rcpp::RNGScope __rngScope;
    Rcpp::traits::input_parameter< float >::type p(pSEXP);
    Rcpp::traits::input_parameter< NumericVector >::type xi(xiSEXP);
    Rcpp::traits::input_parameter< NumericVector >::type g(gSEXP);
    Rcpp::traits::input_parameter< NumericVector >::type k(kSEXP);
    __result = Rcpp::wrap(cppXI0(p, xi, g, k));
    return __result;
END_RCPP
}
// nll_gev
double nll_gev(NumericVector par, Function fpar, NumericMatrix data, NumericVector w);
RcppExport SEXP nim_nll_gev(SEXP parSEXP, SEXP fparSEXP, SEXP dataSEXP, SEXP wSEXP) {
BEGIN_RCPP
    Rcpp::RObject __result;
    Rcpp::RNGScope __rngScope;
    Rcpp::traits::input_parameter< NumericVector >::type par(parSEXP);
    Rcpp::traits::input_parameter< Function >::type fpar(fparSEXP);
    Rcpp::traits::input_parameter< NumericMatrix >::type data(dataSEXP);
    Rcpp::traits::input_parameter< NumericVector >::type w(wSEXP);
    __result = Rcpp::wrap(nll_gev(par, fpar, data, w));
    return __result;
END_RCPP
}
