# This file was generated by Rcpp::compileAttributes
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

cppREG <- function(p, xpar, xi, g, k) {
    .Call('nim_cppREG', PACKAGE = 'nim', p, xpar, xi, g, k)
}

cppREG_lin <- function(p, xpar, xi, g, k) {
    .Call('nim_cppREG_lin', PACKAGE = 'nim', p, xpar, xi, g, k)
}

cppREG_constK <- function(p, xpar, xi, g, k) {
    .Call('nim_cppREG_constK', PACKAGE = 'nim', p, xpar, xi, g, k)
}

cppREG_constGK <- function(p, xpar, xi, g, k) {
    .Call('nim_cppREG_constGK', PACKAGE = 'nim', p, xpar, xi, g, k)
}

cppREG_const <- function(p, xpar, xi, g, k) {
    .Call('nim_cppREG_const', PACKAGE = 'nim', p, xpar, xi, g, k)
}

cppXI0 <- function(p, xi, g, k) {
    .Call('nim_cppXI0', PACKAGE = 'nim', p, xi, g, k)
}

nll_gev <- function(par, fpar, data, w) {
    .Call('nim_nll_gev', PACKAGE = 'nim', par, fpar, data, w)
}

